
name: Anudan Frontend Build

on: [ push ]


jobs:
    run-github-actions: 
        runs-on: ubuntu-latest
        steps:
          - name: checkout source code from master
            uses: action/prabhu9652/anudan-app@master
            run:
              ls
